/*
 * 文件名：XMLStaticInfo.java
 * 版权：Copyright 2013-2014 Huawei Tech. Co. Ltd. All Rights Reserved. 
 * 描述： XMLStaticInfo.java
 * 修改时间：2014-1-9
 * 修改内容：新增
 */
package cn.migu.statemachineframework;

/**
 * 静态XML.
 * 
 * @author  duohaoxue
 * @version  [版本号, 2016年9月13日]
 */
public interface XMLStaticInfo
{
    String BASE = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String XML_ERR = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2<objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String NO_START_STATE = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state>                                           \n" + "    <name>S0</name>                       \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String TOO_MANY_START_STATE = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state  start=\"1\">                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String NO_SUCH_STATE = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S12</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String DUP_SYS_EVENT = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String DUP_STATE_EVENT = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>   \n"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>      \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String ERR_RET_ILL_VAL = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">NULL</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String ERR_RET_DIFF_VAL = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">java.lang.String</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String ERR_RET_DIFF_VAL_IRETINTF = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String LOAD_CLASS_ERROR = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Argxx</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String LOAD_FUNC_CLASS_ERROR = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.SX.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String NO_SUCH_EVENT = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e4</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";

    String NO_STATIC_FUNC = "<root>                                              \n"
            + "<context>cn.migu.statemachineframework.tsuit.ContextInfo</context>           \n"
            + "                                                    \n"
            + "<states>                                            \n"
            + "  <state start=\"1\">                                           \n"
            + "    <name>S0</name>                       \n" + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE1</function>     \n"
            + "        <rettype succval=\"OK\">java.lang.String</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S0.onE2NoStatic</function>     \n"
            + "        <rettype succval=\"0\">int</rettype>     \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S1</name>                                 \n"
            + "    <events>                                        \n"
            + "      <event>                                       \n"
            + "        <name>e1</name>                             \n"
            + "        <objstate>S1</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE1</function>     \n"
            + "        <rettype>cn.migu.statemachineframework.IRetValue</rettype>"
            + "      </event>                                      \n"
            + "      <event>                                       \n"
            + "        <name>e2</name>                             \n"
            + "        <objstate>S2</objstate>                     \n"
            + "        <function>cn.migu.statemachineframework.tsuit.S1.onE2</function>     \n"
            + "        <rettype>careless</rettype>                \n"
            + "      </event>                                      \n"
            + "    </events>                                       \n"
            + "  </state>                                          \n"
            + "                                                    \n"
            + "  <state>                                           \n"
            + "    <name>S2</name>                                 \n"
            + "    <events></events>                               \n"
            + "  </state>                                          \n"
            + "</states>                                           \n"
            + "                                                    \n"
            + "<events>                                            \n"
            + "  <event>                                           \n"
            + "    <name>e1</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E1Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e2</name>                                 \n"
            + "    <arg>cn.migu.statemachineframework.tsuit.E2Arg</arg>                     \n"
            + "  </event>                                          \n"
            + "  <event>                                           \n"
            + "    <name>e3</name>                                 \n"
            + "    <arg>java.lang.Object</arg>                     \n"
            + "  </event>                                          \n"
            + "</events>                                           \n"
            + "</root>                                             \n";
}
